source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "wdm", ">= 0.1.0" if Gem.win_platform?
gem "jekyll-watch"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-paginate"
end
